#workflow GitHub Action Environnement preprod sur azure microsoft !
name: Déploiement préproduction Azure

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Déploiement de l'infra sur Azure
    runs-on: ubuntu-latest

    env:
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_SECRET: ${{ secrets.AZURE_SECRET }}
      AZURE_TENANT: ${{ secrets.AZURE_TENANT }}

    steps:
      - name: Checkout du dépôt
        uses: actions/checkout@v4

      - name: Installation Ansible et dépendances Azure
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install --upgrade pip setuptools wheel
          pip3 install ansible
          pip3 install 'ansible[azure]'
          pip3 install azure-cli
          pip3 install azure-storage-blob
          pip3 install azure.mgmt.automation
          pip3 install azure.mgmt.notificationhubs       
          pip3 install microsoft-kiota-authentication-azure
          pip3 install msgraph-core
          pip3 install 'msgraph-sdk' 'azure.mgmt.resourcehealth'
          pip3 install azure-mgmt-resource azure-mgmt-network azure-mgmt-compute azure-mgmt-rdbms azure-mgmt-datafactory
          pip3 install 'ansible[azure]' 'msrestazure' 'azure-mgmt-resource' 'azure-mgmt-network' 'azure-mgmt-compute' 'azure-mgmt-rdbms' 'azure-identity'
          # ~pip3 install -r https://raw.githubusercontent.com/Azure/azure-sdk-for-python/main/requirements.txt
          ansible-galaxy collection install azure.azcollection --force

      - name: connection à Azure via CLI
        run: |
          az login --service-principal \
            --username "$AZURE_CLIENT_ID" \
            --password "$AZURE_SECRET" \
            --tenant "$AZURE_TENANT"
          az account set --subscription "$AZURE_SUBSCRIPTION_ID"
      - name: Lister les fichiers du repo
        run: ls -R
      - name: Exécution du playbook Ansible
        run: |
          ansible-playbook playbooks/preprod.yaml -e "@vars/preprod-vars.yaml"
